# TraderNotify
# Get notified when a Wandering Trader is in your world!
#
# For support on Discord, https://discord.gg/7cqHVQyFmU
# For issues or requests, https://github.com/ThijmenGThN/TraderNotify/issues/new



# Broadcast Message
# ~ Set a message that should appear once a wandering trader appears in your world.
message: "&dA Wandering Trader has appeared!"



# Developers workspace
# ~ Normal users won't need to toggle this.
debug: false